version: '3.9'

services:
  db:
    image: postgres:15
    container_name: testproject
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpass
      POSTGRES_DB: testproject
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5433
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: